---
version: '3.4'
services:
  discord-radio-bot:
    image: pace23pace/discord-radio-bot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: discord-radio-bot
    environment:
    - TZ=UTC
    network_mode: bridge
    volumes:
    - ./config.json:/app/config.json
    restart: unless-stopped
